### ISSUE TITLE
AudioSet label index mapping is missing

### ISSUE THREAD

**Issue by gevmin94** [K-H-Ismail/DCLS-Audio#2]
Please provide label index mapping of AudioSet for the inference.

**Comment by K-H-Ismail** [comment]
Hello,

I was unable to provide the full dataset as I encountered problems with Youtube copyright. However, if you are asking about the correspondence between the numerical labels (from 0 to 526) and the textual labels (Speech, ..., Field recording) we used this one [class_labels_indices.csv](https://github.com/qiuqiangkong/audioset_tagging_cnn/blob/master/metadata/class_labels_indices.csv).
In general, you can find information on how to download / organize the data here:
[PANN](https://github.com/qiuqiangkong/audioset_tagging_cnn/tree/master).
